SION/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login.urls as login
import registrasi_user.urls as registrasi_user
import profil_organisasi.urls as profil_organisasi
import donasi_organisasi.urls as donasi_organisasi
import profil_user.urls as profil_user
import regis_organisasi.urls as regis_organisasi
import logout.urls as logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login, namespace='login')),
    url(r'^registrasi_user/', include(registrasi_user, namespace='registrasi-user')),
    url(r'^profil_organisasi/', include(profil_organisasi, namespace='profil-organisasi')),
    url(r'^donasi_organisasi/', include (donasi_organisasi, namespace='donasi-organisasi')),
    url(r'^profil_user/', include(profil_user, namespace='profil-user')),
    url(r'^regis_organisasi/', include(regis_organisasi, namespace='regis-organisasi')),
    url(r'^logout/',  include(logout, namespace='logout')),
    url(r'^$', RedirectView.as_view(url="/login/", permanent="true"), name='index'),
     
]

templates/partials/footer.html
<div class="footer">
  <div class="container-fluid text-center">
  		<div class="row">
  			<div class="cr">
  				<p>Copyright &copy; 2018</p>
  			</div>
  	</div>
  </div>
</div>

templates/partials/header.html
{% block css %}
<style>

.nav>li>a:focus, .nav>li>a:hover {
    text-decoration: none;
    background-color: #eee;
    color: #F38181;
}

#nama{
	border:2px solid #FBFBFB;
	padding-left:2px;
	padding-right:2px;
	float:left;
	margin-top:12px;
	margin-right:8px;
	font-family: 'Pacifico', cursive;
    }

    .nav-link:active, .nav-link{
        color:aliceblue;
    }

    .nav-link:hover{
        color: #FBFBFB;
    }
    
    .nav-item{
        font-size: 13px;
    }
    .float-right{
        float: right;
    }

    #content{
        padding-top: 50px;
    }
    
    #nama:visited, #nama:link, #nama:hover{
	    color:#FBFBFB;
    }

    .container{
        padding-top:10px;
        padding-bottom:10px;
    }


    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }

.navbar{
    background-color: #F38181 !important;
}

footer{
    position: fixed;
    bottom: 0px;
    width: 100%;
    background-color: #756C83;
    color: #fbfbfb;
}

.fa-bars{
    color: white;
    font-size: 25px;
}

#content{
    margin-bottom:30px;
    
}

.head{
    padding-bottom:30px;
    padding-top: 10px;
    text-align: center;
    text-shadow: 3px 3px #756C83;
    color: #FBFBFB;

}

.btn-submit{
    background-color:  #756C83;
    color: white;
}

.submit{
    justify-content: flex-end;
    display: flex;
}
.btn-submit{
    background-color:  #756C83;
    color: white;
}

.submit{
    justify-content: flex-end;
    display: flex;
}
</style>
{% endblock %}

<nav class="navbar navbar-expand-lg fixed-top">
    <div id="navbar-collapsed" class="collapse navbar-collapse float-xs-left">
      
        <a id="nama" href={% url 'index' %} style="color: #FBFBFB">SION</a>

      <ul class="nav navbar-nav float-xs-left">

        {% if role == relawan %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'profil-user:index' %}" role="button" aria-haspopup="true" aria-expanded="false">
                Profil</a>  
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'profil-organisasi:index' %}" role="button" aria-haspopup="true" aria-expanded="false">
                Lihat Organisasi</a>  
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'donasi-organisasi:index' %}" role="button" aria-haspopup="true" aria-expanded="false">
                Berdonasi ke Organisasi</a>  
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#!" role="button" aria-haspopup="true" aria-expanded="false">
                Berdonasi ke Kegiatan</a>  
            </li>
        {% elif role == donatur %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'profil-user:index' %}" role="button" aria-haspopup="true" aria-expanded="false">
                Profil</a>  
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'profil-organisasi:index' %}" role="button" aria-haspopup="true" aria-expanded="false">
                Lihat Organisasi</a>  
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'donasi-organisasi:index' %}" role="button" aria-haspopup="true" aria-expanded="false">
                Berdonasi ke Organisasi</a>  
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#!" role="button" aria-haspopup="true" aria-expanded="false">
                Berdonasi ke Kegiatan</a>  
            </li>
        {% elif role == sponsor %}
            <li class="nav-item">
            <a class="nav-link"  href="{% url 'profil-user:index' %}" role="button" aria-haspopup="true" aria-expanded="false">
                Profil</a>  
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'profil-organisasi:index' %}" role="button" aria-haspopup="true" aria-expanded="false">
                Lihat Organisasi</a>  
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'donasi-organisasi:index' %}" role="button" aria-haspopup="true" aria-expanded="false">
                Berdonasi ke Organisasi</a>  
            </li>
        {% elif role == pengurus %}
            <li class="nav-item">
            <a class="nav-link" href="#!" role="button" aria-haspopup="true" aria-expanded="false">
                Profil</a>  
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'profil-organisasi:index' %}" role="button" aria-haspopup="true" aria-expanded="false">
                Lihat Organisasi</a>  
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#!" role="button" aria-haspopup="true" aria-expanded="false">
                Buat Kegiatan</a>  
            </li>
            <li class="nav-item">
            <a class="nav-link" href="#!" role="button" aria-haspopup="true" aria-expanded="false">
                Lihat Kegiatan</a>  
            </li>
        {% endif %}
      </ul> 
      <div class="ml-auto">
        <ul class="nav navbar-nav float-right" >
        {% if role != sponsor %}
        <li class="nav-item float-right">
        <a class="nav-link" href="{% url 'regis-organisasi:index' %}" role="button" aria-haspopup="true" aria-expanded="false">
            Registrasi Organisasi</a>  
        </li>
        {% endif %}
         <li class="nav-item float-right">
          <a class="nav-link" href='{% url "logout:index" %}' role="button" aria-haspopup="true" aria-expanded="false">
            Logout</a>  
        </li>
      </ul> 
    </div> 

</nav>