SION/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login.urls as login
import registrasi_user.urls as registrasi_user
import profil_organisasi.urls as profil_organisasi
import donasi_organisasi.urls as donasi_organisasi
import profil_user.urls as profil_user
import regis_organisasi.urls as regis_organisasi
import logout.urls as logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login, namespace='login')),
    url(r'^registrasi_user/', include(registrasi_user, namespace='registrasi-user')),
    url(r'^profil_organisasi/', include(profil_organisasi, namespace='profil-organisasi')),
    url(r'^donasi_organisasi/', include (donasi_organisasi, namespace='donasi-organisasi')),
    url(r'^profil_user/', include(profil_user, namespace='profil-user')),
    url(r'^regis_organisasi/', include(regis_organisasi, namespace='regis-organisasi')),
    url(r'^logout/',  include(logout, namespace='logout')),
    url(r'^$', RedirectView.as_view(url="/login/", permanent="true"), name='index'),
     
]

login/urls.py
from django.conf.urls import url
from .views import index, auth_login

app_name='login'

urlpatterns=[
    url(r'^$', index, name='index'),
    url(r'^auth-login', auth_login, name='auth-login')
]

login/views.py
from django.shortcuts import render
from django.db import connection
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect, csrf_exempt

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

# Create your views here.
def index(request):
    if ('islogout' in request.session.keys()):
        request.session.flush()
    if 'user' in request.session.keys():
        request.session['first_view_profil']=True
        print("login ", request.session['first_view_profil'])
        return HttpResponseRedirect(reverse('profil-user:index'))
    else:
        html='login/index.html'
        return render(request, html)

@csrf_exempt
def auth_login(request):
    user={}
    if request.method == "POST":
        username = request.POST['email']
        password = request.POST['password']

        cur=connection.cursor()
        isValid=False

        print("masuk")
        # Cek for Sponsor 
        cur.execute('SELECT * FROM "USER" WHERE password=%s AND email IN (SELECT email FROM SPONSOR WHERE email=%s);', (password, username))
        getUser=dictfetchall(cur)
        if(len(getUser)!=0):
            user=getUser[0]
            request.session['role']='sponsor'
            isValid=True

        # Cek for donatur 
        if not(isValid):
            cur.execute('SELECT * FROM "USER" WHERE password=%s AND email IN (SELECT email FROM DONATUR WHERE email=%s);', (password, username))
            getUser=dictfetchall(cur)
            if(len(getUser)!=0):
                user=getUser[0]
                request.session['role']='donatur'
                isValid=True

        # Cek for relawan 
        if not(isValid):
            cur.execute('SELECT * FROM "USER" WHERE password=%s AND email IN (SELECT email FROM RELAWAN WHERE email=%s);', (password, username))
            getUser=dictfetchall(cur)
            print(getUser)
            print("relawan")
            print(getUser)
            if(len(getUser)!=0):
                user=getUser[0]
                request.session['role']='relawan'
                isValid=True
    
        # Cek for pengurus 
        if not(isValid):
            cur.execute('SELECT * FROM "USER" WHERE password=%s AND email IN (SELECT email FROM pengurus_organisasi WHERE email=%s);', (password, username))
            getUser=dictfetchall(cur)
            if(len(getUser)!=0):
                user=getUser[0]
                request.session['role']='pengurus'
                isValid=True

        if not(isValid):
            messages.error(request, "Username atau password salah")
        else:
            request.session['user'] = user
            print(request.session['user'])
            
    return HttpResponseRedirect(reverse('login:index'))

login/templates/login/index.html
{% extends "login/layout/base.html" %}

{% load static %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'login/css/style.css' %}" />
{% endblock %}

{% block content %}

{% block header %}
{% include 'login/layout/header-hanifa.html' %}
{% endblock%}

<div class="container">
  <div class="head">
      <h1>SELAMAT DATANG DI SION!</h1>
      <h2>(Sistem Informasi Organisasi Nirlaba)</h2>      
  </div>
  
  <div class="login-form">
    <h3 id="login-h3">LOGIN</h3>
    <div>
        <form method="POST" action="{% url 'login:auth-login' %}">
          {% csrf_token %}
          <div class="form-group row">
            <label for="exampleInputEmail1" class="col-sm-3 col-form-label">Email address</label>
            <div class="col-sm-9">
                <input name='email' type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
            </div>
            <span class="col-sm-3"></span>
            <small id="emailHelp" class="form-text text-muted col-sm-9">We'll never share your email with anyone else.</small>
          </div>
          <div class="form-group row">
            <label for="inputPassword" class="col-sm-3 col-form-label">Password</label>
            <div class="col-sm-9">
              <input name="password" type="password" class="form-control" id="inputPassword" placeholder="Password">
            </div>
          </div>
          <div class="submit">
              <button type="submit" class="btn btn-primary btn-submit">Submit</button>
          </div>
        </form>
    </div>
    <p id="no-account">
        Tidak punya akun? <a href={% url 'registrasi-user:index' %}>Registrasi User disini.</a> 
      </p>
  </div>
  




</div>

{% endblock %}