SION/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login.urls as login
import registrasi_user.urls as registrasi_user
import profil_organisasi.urls as profil_organisasi
import donasi_organisasi.urls as donasi_organisasi
import profil_user.urls as profil_user
import regis_organisasi.urls as regis_organisasi
import logout.urls as logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(login, namespace='login')),
    url(r'^registrasi_user/', include(registrasi_user, namespace='registrasi-user')),
    url(r'^profil_organisasi/', include(profil_organisasi, namespace='profil-organisasi')),
    url(r'^donasi_organisasi/', include (donasi_organisasi, namespace='donasi-organisasi')),
    url(r'^profil_user/', include(profil_user, namespace='profil-user')),
    url(r'^regis_organisasi/', include(regis_organisasi, namespace='regis-organisasi')),
    url(r'^logout/',  include(logout, namespace='logout')),
    url(r'^$', RedirectView.as_view(url="/login/", permanent="true"), name='index'),
     
]

registrasi_user/urls.py
from django.conf.urls import url
from .views import index, form_donatur, form_relawan, form_sponsor, regis_donatur, regis_sponsor, regis_relawan

app_name='registrasi_user'

urlpatterns=[
    url(r'^$', index, name='index'),
    url(r'^donatur', form_donatur, name='form-donatur'),
    url(r'^sponsor', form_sponsor, name='form-sponsor'),
    url(r'^relawan', form_relawan, name='form-relawan'),
    url(r'^regis-donatur', regis_donatur, name='regis-donatur'),
    url(r'^regis-sponsor', regis_sponsor, name='regis-sponsor'),
    url(r'^regis-relawan', regis_relawan, name='regis-relawan')
]

registrasi_user/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from datetime import date

cur=connection.cursor()

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

# Create your views here.
def index(request):
    html = 'registrasi_user/index.html'
    context = {
        'role':'',
        'relawan':'relawan',
        'sponsor':'sponsor',
        'donatur':'donatur'
    }
    return render(request, html, context)

def form_donatur(request):
    html = 'registrasi_user/index.html'
    context={
        'role':'Donatur',
        'relawan':'Relawan',
        'sponsor':'Sponsor',
        'donatur':'Donatur'
    }
    return render(request, html, context)

def form_sponsor(request):
    html = 'registrasi_user/index.html'
    context={
        'role':'Sponsor',
        'relawan':'Relawan',
        'sponsor':'Sponsor',
        'donatur':'Donatur'
    }
    return render(request, html, context)

def form_relawan(request):
    html = 'registrasi_user/index.html'
    context={
        'role':'Relawan',
        'relawan':'Relawan',
        'sponsor':'Sponsor',
        'donatur':'Donatur'
    }
    return render(request, html, context)

def insert_user(email, password, name, alamat):
        if ((password!="") & (alamat!="") & (name!="")):
            query= 'INSERT INTO "USER" (email, password, nama, alamat_lengkap) VALUES(%s,%s,%s,%s)'
            data= (email, password, name, alamat)
            cur.execute(query, data)
            print("commit regis")
            query='SELECT * FROM "USER" WHERE email=%s'
            data=(email,)
            cur.execute(query, data)
            print(cur.fetchone())
        else:
            messages.error(request, "Input tidak boleh ada yang kosong")

def regis_user(request, email):
    print("masuk regis user")
    # try:
    
    isValid=True
    # cur.execute('SELECT * FROM "USER"')
    # print(cur.fetchall())
    query='SELECT * FROM "USER" WHERE email=%s'
    data=(email,)
    cur.execute(query, data)
    getUser=dictfetchall(cur)
    print(getUser)
    
    if (len(getUser)!=0):
        print("masuk false")
        user=getUser[0]
        isValid=False
        messages.error(request, "Tidak dapat menggunakan username tersebut")
    return isValid

@csrf_protect
def regis_donatur(request):
    print("masuk regis_donatur")
    if request.method == 'POST':
        print("masuk post")
        email=request.POST['email']
        password=request.POST['password']
        nama = request.POST['name']
        alamat=request.POST['alamat']+', '+request.POST['kecamatan']+', '+request.POST['kabupaten']+", "+request.POST['provinsi']+", "+request.POST['kodepos']

        if (regis_user(request, email)): 
            query = 'SELECT * FROM "USER" WHERE email IN (SELECT email FROM DONATUR WHERE email=%s)'
            data = (email, )
            cur.execute(query, data)
            getUser=dictfetchall(cur)
            print("donatur udah ada: ",getUser)
            if (len(getUser)!=0):
                print("masuk false")
                user=getUser[0]
                messages.error(request, "Tidak dapat menggunakan username tersebut")

            else:
                insert_user(email, password, nama, alamat)
                connection.commit()
                query = 'INSERT INTO DONATUR (email, saldo) VALUES(%s,0)'
                data = (email,)
                cur.execute(query, data)
                connection.commit()
                
                query='SELECT * FROM DONATUR WHERE email=%s'
                cur.execute(query, data)

                request.session['user']=dictfetchall(cur)
                print(request.session['user'])
                request.session['role']='donatur'

                messages.success(request, "Selamat! Kamu berhasil mendaftar.")
                return HttpResponseRedirect(reverse('login:auth-login'))
    return HttpResponseRedirect(reverse('registrasi-user:form-donatur'))

@csrf_exempt
def regis_sponsor(request):
    print("----> Masuk regis_sponsor")
    if request.method == 'POST':
        print("masuk post")
        email=request.POST['email']
        password=request.POST['password']
        nama = request.POST['name']
        alamat=request.POST['alamat']+', '+request.POST['kecamatan']+', '+request.POST['kabupaten']+", "+request.POST['provinsi']+", "+request.POST['kodepos']
        logo=request.POST['logo']

        isValid=regis_user(request, email)

        if (isValid & (logo!="")): 
            query = 'SELECT * FROM "USER" WHERE email IN (SELECT email FROM SPONSOR WHERE email=%s)'
            data = (email, )
            cur.execute(query, data)
            getUser=dictfetchall(cur)
            print("sponsor udah ada: ",getUser)
            if (len(getUser)!=0):
                print("masuk false")
                user=getUser[0]
                messages.error(request, "Tidak dapat menggunakan username tersebut")

            else:
                insert_user(email, password, nama, alamat)
                connection.commit()
                query = 'INSERT INTO SPONSOR (email, logo_sponsor) VALUES(%s, %s)'
                data = (email, logo)
                cur.execute(query, data)
                connection.commit()

                query='SELECT * FROM SPONSOR WHERE email=%s'
                data=(email,)
                cur.execute(query, data)

                request.session['user']=dictfetchall(cur)
                print(request.session['user'])
                request.session['role']='sponsor'

                messages.success(request, "Selamat! Kamu berhasil mendaftar.")
                return HttpResponseRedirect(reverse('login:auth-login'))
        elif not(isValid):
            return HttpResponseRedirect(reverse('registrasi-user:form-sponsor'))
        
        messages.error(request,'Gak boleh ada field yang kosong yaa')
        return HttpResponseRedirect(reverse('registrasi-user:form-sponsor'))

@csrf_exempt
def regis_relawan(request):
    print("----> Masuk regis_relawan")
    if request.method == 'POST':
        print("masuk post")
        email=request.POST['email']
        password=request.POST['password']
        nama = request.POST['name']
        alamat=request.POST['alamat']+', '+request.POST['kecamatan']+', '+request.POST['kabupaten']+", "+request.POST['provinsi']+", "+request.POST['kodepos']
        nohp=request.POST['nohp']
        ttl=request.POST['ttl']
        keahlian=request.POST['keahlian']
        print(type(ttl))
        
        isValid=regis_user(request, email)

        if ( isValid & (nohp!="") & (ttl!="") & (keahlian!="")): 
            query = 'SELECT * FROM "USER" WHERE email IN (SELECT email FROM RELAWAN WHERE email=%s)'
            data = (email, )
            cur.execute(query, data)
            getUser=dictfetchall(cur)
            print("sponsor udah ada: ",getUser)
            if(len(getUser)!=0):
                print("masuk false")
                user=getUser[0]
                messages.error(request, "Tidak dapat menggunakan username tersebut")

            else:
                insert_user(email, password, nama, alamat)
                query = 'INSERT INTO RELAWAN (email, no_hp, tanggal_lahir) VALUES(%s, %s, %s)'
                data = (email, nohp, ttl)
                cur.execute(query, data)
                connection.commit()
                query = 'INSERT INTO KEAHLIAN_RELAWAN (email, keahlian) VALUES(%s, %s)'
                data = (email, keahlian)
                cur.execute(query, data)
                connection.commit()
                print("masuk relawan commit")
                
                query='SELECT * FROM RELAWAN WHERE email=%s'
                data=(email,)
                cur.execute(query, data)
                user = dictfetchall(cur)[0]
                user['tanggal_lahir']=user.get('tanggal_lahir').isoformat()
                request.session['user']=user
                print("blabla ", request.session['user'])
                request.session['role']='relawan'

                messages.success(request, "Selamat! Kamu berhasil mendaftar.")

                return HttpResponseRedirect(reverse('login:auth-login'))
            return HttpResponseRedirect(reverse('registrasi-user:form-relawan'))
        elif not(isValid):        
            return HttpResponseRedirect(reverse('registrasi-user:form-relawan'))
        else:
            messages.error(request,'Gak boleh ada field yang kosong yaa')
            return HttpResponseRedirect(reverse('registrasi-user:form-relawan'))

registrasi_user/templates/registrasi_user/user/donatur.html
<!-- Nama: [Isian]
Email: [Isian]
Password: [Isian]
Kecamatan: [Isian]
Kabupaten: [Isian]
Provinsi: [Isian]
Kode Pos: [Isian]
Jalan/Desa/Keluarahan/No.Rumah: [Isian] -->

<form method="POST" action="{% url 'registrasi-user:regis-donatur' %}">
    {% csrf_token %}
    <div class="form-row">
        {% include 'registrasi_user/user/user.html' %}
        <input type="hidden" name="role" value="donatur">
        <div class="submit">
            <button type="submit" class="btn btn-primary btn-submit">Submit</button>
        </div>
    </div>
</form>

registrasi_user/templates/registrasi_user/user/relawan.html
<!-- Nama: [Isian]
Email: [Isian]
Password: [Isian]
Kecamatan: [Isian]
Kabupaten: [Isian]
Provinsi: [Isian]
Kode Pos: [Isian]
Jalan/Desa/Keluarahan/No.Rumah: [Isian]
Tanggal Lahir: [Isian tanggal]
Nomor Handphone: [Isian]
Keahlian yang Dimiliki: [Isian] -->
<form method="POST" action="{% url 'registrasi-user:regis-relawan' %}">
    {% csrf_token %}
    <div class="form-row">
        {% include 'registrasi_user/user/user.html' %}
        <input type="hidden" name="role" value="relawan">
        <div class="form-group">
            <label for="tl-relawan">Tanggal Lahir</label>
            <input name='ttl' type="date" class="form-control" id="tl-relawan" placeholder="Tanggal Lahir">
        </div>
        <div class="form-group">
            <label for="nohp-relawan">Nomor Handphone</label>
            <input name='nohp' type="text" class="form-control" id="nohp-relawan" placeholder="Nomor Handphone">
        </div>
        <div class="form-group">
            <label for="keahlian-relawan">Keahlian</label>
            <input name='keahlian' type="text" class="form-control" id="keahlian-relawan" placeholder="Keahlian yang dimiliki...">
        </div>
        <div class="submit">
            <button type="submit" class="btn btn-primary btn-submit">Submit</button>
        </div>
    </div>
</form>

registrasi_user/templates/registrasi_user/user/sponsor.html
<!-- Nama Sponsor: [Isian]
Email: [Isian]
Password: [Isian]
Kecamatan: [Isian]
Kabupaten: [Isian]
Provinsi: [Isian]
Kode Pos: [Isian]
Jalan/Desa/Keluarahan/No.Rumah: [Isian]
Logo: [Upload file] -->

<form method="POST" action="{% url 'registrasi-user:regis-sponsor' %}">
    {% csrf_token %}
    <div class="form-row">
        {% include 'registrasi_user/user/user.html' %}    
        <input type="hidden" name="role" value="sponsor">   
        <div class="form-group">
            <label>Logo</label>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">Upload</span>
                </div>
                <div class="custom-file">
                    <input name="logo" type="file" class="custom-file-input" id="inputGroupFile01">
                    <label class="custom-file-label" for="inputGroupFile01">Upload your logo</label>
                </div>
            </div>
            <div class="submit">
                <button type="submit" class="btn btn-primary btn-submit">Submit</button>
            </div>
        </div>
    </div>
    
</form>

registrasi_user/templates/registrasi_user/user/user.html
<div class="form-group col-md-12">
    <label for="name">Nama</label>
    <input name='name' type="text" class="form-control" id="name" placeholder="Nama">
</div>
<div class="form-group col-md-6">
    <label for="email">Email</label>
    <input name='email' type="email" class="form-control" id="email" placeholder="Email">
</div>
<div class="form-group col-md-6">
    <label for="password">Password</label>
    <input name="password" type="password" class="form-control" id="password" placeholder="Password">
    </div>
</div>
<div class="form-group">
    <label for="kecamatan">Kecamatan</label>
    <input name='kecamatan' type="text" class="form-control" id="kecamatan" placeholder="Kecamatan">
</div>
<div class="form-group">
    <label for="kabupaten">Kabupaten</label>
    <input name='kabupaten' type="text" class="form-control" id="kabupaten" placeholder="Kabupaten">
</div>
<div class="form-group">
    <label for="provinsi">Provinsi</label>
    <input name='provinsi' type="text" class="form-control" id="provinsi" placeholder="provinsi">
</div>
<div class="form-group">
    <label for="kodepos-relawan">Kode Pos</label>
    <input name="kodepos" type="text" class="form-control" id="kodepos-relawan" placeholder="kode pos">
</div>
<div class="form-group">
    <label for="alamat">Alamat</label>
    <input name='alamat' type="text" class="form-control" id="alamat" placeholder="Jalan/Desa/Keluarahan/No.Rumah">
</div>

    